services:
  db: 
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD_REG_USER}
    ports:
      - '3306:3306'
    volumes:
      - reskilled_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", 'ping', '-h', '${DATABASE_HOST}', '-u${DATABASE_USER}', '-p${DATABASE_PASSWORD}']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s
volumes:
    reskilled_db: